#!/bin/zsh

COMMIT_MSG_FILE=$1
COMMIT_MSG_CONTENT=$(cat "$COMMIT_MSG_FILE")

# Get the current branch name and check if it is excluded
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Trim it down to get the parts we're interested in
TICKET_NUMBER=$(echo "$BRANCH_NAME" | sed -n -E 's:([a-zA-Z]+/)*([a-zA-Z]+-[0-9]+).*:\2:p')
# Also extract release number
RELEASE_NUMBER=$(echo "$BRANCH_NAME" | sed -n -E 's:([a-zA-Z]+/)*([a-zA-Z]+-[0-9]+)-([0-9]+\.[0-9]+).*:\3:p')
# Prepend the release number identifier to the given message
if [[ $RELEASE_NUMBER != '' && $COMMIT_MSG_CONTENT != "["* && $COMMIT_MSG_CONTENT != " "* ]]; then sed -i.bak -e "1s/^/[$RELEASE_NUMBER] /" "$COMMIT_MSG_FILE"; fi
# Prepend the ticket number identifier to the given message
if [[ $TICKET_NUMBER != '' && $COMMIT_MSG_CONTENT != "["* && $COMMIT_MSG_CONTENT != " "* ]]; then sed -i.bak -e "1s/^/[$TICKET_NUMBER] /" "$COMMIT_MSG_FILE"; fi
